version: '2'
services:
    web:
        image: {{ cookiecutter.docker_user }}/{{ cookiecutter.docker_repo }}:{{ cookiecutter.docker_tag }}
        ports:
            - "80:5000"
        environment:
            WEBEX_TEAMS_ACCESS_TOKEN: <insert_access_token_here>
            REMOTE_PREFIX: <insert_remote_prefix_here>